
development:
  username: ["theprogrammerin"]
  token: "<%= ENV["GITHUB_TOKEN"] %>"
  repos: ["git-wf"]
  events: ["create", "pull_request"]
  notification_issues:
    invalid_branch_name: 5


production:
  username: ["theprogrammerin"]
  token: "<%= ENV["GITHUB_TOKEN"] %>"
  repos: ["git-wf"]
  events: ["create", "pull_request"]
  notification_issues:
    invalid_branch_name: 5

