
development:
  username: ["theprogrammerin"]
  token: "<%= ENV["GITHUB_TOKEN"] %>"
  repos: ["git-wf"]
  events: ["create", "pull_request"]


production:
  username: ["theprogrammerin"]
  token: "<%= ENV["GITHUB_TOKEN"] %>"
  repos: ["git-wf"]
  events: ["create", "pull_request"]

