# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68385ba7499257d75cb699e89dc3e48fb2dfd0e8ba9271aaaaec56f2c0d8b00ac1fd1f3ff97471f19f756189a21cedd08ca7d9880bf9bc9a411441b331f3db9b

test:
  secret_key_base: 55348c763121fd417781705d926499dd916ef35eb9677a4ac40dbbd6fe75a833ec511cf40dcd3fc112eba932e3e4ae000ff135b0cec7ad98b02429f9214304ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
